tags:
  - 2024政見
  - 2024帶公職參選
  - 性別
  - 生日
  - 出生地
  - 學歷
  - 家庭背景
  - 從政經歷
  - 目前政黨
  - 宗教信仰
  - 兩岸主張
  - 性平主張
  - 前科
  - Meme迷因

politician_groups:
  2024_總統:
    keys: []
    value: ['侯友宜', '趙少康', '賴清德', '蕭美琴', '柯文哲', '吳欣盈']
  2024_立委_不分區_中國國民黨:
    keys: []
    value: []
  2024_立委_不分區_民主進步黨:
    keys: []
    value: []
  2024_立委_不分區_時代力量:
    keys: []
    value: []
  2024_立委_不分區_台灣民眾黨:
    keys: []
    value: []
  2024_立委_臺北市_第一選舉區:
    keys: ['北投區', '士林區']
    value: ['吳思瑤', '張斯綱', '侯漢廷']
  2024_立委_臺北市_第二選舉區:
    keys: ['大同區', '士林區']
    value: ['王世堅', '游淑慧']
  2024_立委_臺北市_第三選舉區:
    keys: ['中山區', '松山區']
    value: ['謝佩芬', '王鴻薇']
  2024_立委_臺北市_第四選舉區:
    keys: ['內湖區', '南港區']
    value: ['高嘉瑜', '李彥秀', '吳欣岱']
  2024_立委_臺北市_第五選舉區:
    keys: ['萬華區', '中正區']
    value: ['吳沛憶', '鍾小平', '于美人']
  2024_立委_臺北市_第六選舉區:
    keys: ['大安區']
    value: ['苗博雅', '羅智強']
  2024_立委_臺北市_第七選舉區:
    keys: ['信義區', '松山區']
    value: ['許淑華', '徐巧芯']
  2024_立委_臺北市_第八選舉區:
    keys: ['文山區', '中正區']
    value: ['王閔生', '賴士葆', '賴宣任', '張其祿']
  2024_立委_新北市_第一選舉區:
    keys: ['石門區', '三芝區', '淡水區', '八里區', '林口區', '泰山區']
    value: ['何博文', '洪孟楷']
  2024_立委_新北市_第二選舉區:
    keys: ['五股區', '蘆洲區', '三重區']
    value: ['林淑芬', '李有宜']
  2024_立委_新北市_第三選舉區:
    keys: ['三重區']
    value: ['李坤城', '蔡明堂']
  2024_立委_新北市_第四選舉區:
    keys: ['新莊區']
    value: ['吳秉叡', '蔣欣璋']
  2024_立委_新北市_第五選舉區:
    keys: ['樹林區', '鶯歌區', '新莊區']
    value: ['蘇巧慧', '洪佳君']
  2024_立委_新北市_第六選舉區:
    keys: ['板橋西區']
    value: ['張宏陸', '林國春']
  2024_立委_新北市_第七選舉區:
    keys: ['板橋東區']
    value: ['羅致政', '葉元之', '劉書婷']
  2024_立委_新北市_第八選舉區:
    keys: ['中和區']
    value: ['吳崢', '張智倫', '邱臣遠']
  2024_立委_新北市_第九選舉區:
    keys: ['永和區', '中和區']
    value: ['莊銘淵', '林德福']
  2024_立委_新北市_第十選舉區:
    keys: ['土城區', '三峽區']
    value: ['吳琪銘', '林金結']
  2024_立委_新北市_第十一選舉區:
    keys: ['新店區', '深坑區', '石碇區', '坪林區', '烏來區']
    value: ['曾柏瑜', '羅明才']
  2024_立委_新北市_第十二選舉區:
    keys: ['汐止區', '金山區', '萬里區', '瑞芳區', '平溪區', '雙溪區', '貢寮區']
    value: ['賴品妤', '廖先翔']
  2024_立委_桃園市_第一選舉區:
    keys: ['蘆竹區', '龜山區', '桃園區']
    value: ['鄭運鵬', '牛煦庭', '徐鈺雯']
  2024_立委_桃園市_第二選舉區:
    keys: ['楊梅區', '新屋區', '觀音區', '大園區']
    value: ['黃世杰', '涂權吉']
  2024_立委_桃園市_第三選舉區:
    keys: ['中壢區']
    value: ['彭俊豪', '魯明哲', '徐鶯慈']
  2024_立委_桃園市_第四選舉區:
    keys: ['桃園區']
    value: ['范綱祥', '萬美玲']
  2024_立委_桃園市_第五選舉區:
    keys: ['平鎮區', '龍潭區']
    value: ['劉仁照', '呂玉玲', '賴香伶']
  2024_立委_桃園市_第六選舉區:
    keys: ['八德區', '大溪區', '復興區', '中壢區']
    value: ['趙正宇', '邱若華', '李慕妍']
  2024_立委_臺中市_第一選舉區:
    keys: ['大甲區', '大安區', '外埔區', '清水區', '梧棲區']
    value: ['蔡其昌', '劉燈鐘', '蔡壁如']
  2024_立委_臺中市_第二選舉區:
    keys: ['沙鹿區', '龍井區', '大肚區', '烏日區', '霧峰區']
    value: ['林靜儀', '顏寬恆']
  2024_立委_臺中市_第三選舉區:
    keys: ['后里區', '神岡區', '大雅區', '潭子區']
    value: ['謝子涵', '楊瓊瓔']
  2024_立委_臺中市_第四選舉區:
    keys: ['西屯區', '南屯區']
    value: ['張廖萬堅', '廖偉翔']
  2024_立委_臺中市_第五選舉區:
    keys: ['北屯區', '北區']
    value: ['莊競程', '黃健豪', '蔡善雯']
  2024_立委_臺中市_第六選舉區:
    keys: ['東區', '南區', '中區', '西區']
    value: ['江肇國', '羅廷瑋']
  2024_立委_臺中市_第七選舉區:
    keys: ['太平區', '大里區']
    value: ['何欣純', '林家興']
  2024_立委_臺中市_第八選舉區:
    keys: ['豐原區', '石岡區', '東勢區', '新社區', '和平區']
    value: ['謝志忠', '江啟臣']
  2024_立委_臺南市_第一選舉區:
    keys:
      [
        '後壁區',
        '白河區',
        '北門區',
        '學甲區',
        '鹽水區',
        '新營區',
        '柳營區',
        '東山區',
        '將軍區',
        '下營區',
        '六甲區',
      ]
    value: ['賴惠員', '周宏昌']
  2024_立委_臺南市_第二選舉區:
    keys:
      [
        '七股區',
        '佳里區',
        '麻豆區',
        '官田區',
        '善化區',
        '大內區',
        '玉井區',
        '楠西區',
        '西港區',
        '安定區',
        '山上區',
        '左鎮區',
        '南化區',
      ]
    value: ['郭國文', '陳昆和']
  2024_立委_臺南市_第三選舉區:
    keys: ['安南區', '北區']
    value: ['陳亭妃', '姚正玉']
  2024_立委_臺南市_第四選舉區:
    keys: ['新市區', '永康區', '新化區']
    value: ['林宜瑾', '李全教']
  2024_立委_臺南市_第五選舉區:
    keys: ['安平區', '中西區', '南區', '東區']
    value: ['林俊憲', '王家貞']
  2024_立委_臺南市_第六選舉區:
    keys: ['仁德區', '歸仁區', '關廟區', '龍崎區', '東區']
    value: ['王定宇', '陳以信', '陳永和']
  2024_立委_高雄市_第一選舉區:
    keys:
      [
        '甲仙區',
        '六龜區',
        '杉林區',
        '內門區',
        '大樹區',
        '大社區',
        '旗山區',
        '美濃區',
        '茂林區',
        '阿蓮區',
        '田寮區',
        '燕巢區',
        '桃源區',
        '那瑪夏區',
      ]
    value: ['邱議瑩', '曾尹儷']
  2024_立委_高雄市_第二選舉區:
    keys:
      [
        '茄萣區',
        '湖內區',
        '路竹區',
        '永安區',
        '岡山區',
        '彌陀區',
        '梓官區',
        '橋頭區',
      ]
    value: ['邱志偉', '曹桓榮']
  2024_立委_高雄市_第三選舉區:
    keys: ['楠梓區', '左營區']
    value: ['李柏毅', '李眉蓁']
  2024_立委_高雄市_第四選舉區:
    keys: ['仁武區', '鳥松區', '大寮區', '林園區']
    value: ['林岱樺', '陳若翠']
  2024_立委_高雄市_第五選舉區:
    keys: ['三民區', '苓雅區']
    value: ['李昆澤', '黃柏霖', '張芳愉']
  2024_立委_高雄市_第六選舉區:
    keys: ['鼓山區', '鹽埕區', '前金區', '新興區', '苓雅區']
    value: ['黃捷', '陳美雅', '郭倍宏']
  2024_立委_高雄市_第七選舉區:
    keys: ['鳳山區']
    value: ['許智傑', '鍾易仲']
  2024_立委_高雄市_第八選舉區:
    keys: ['旗津區', '前鎮區', '小港區']
    value: ['賴瑞隆', '李明璇']
  2024_立委_基隆市:
    keys: []
    value: ['鄭文婷', '王醒之', '謝海菁', '林沛祥']
  2024_立委_宜蘭縣:
    keys: []
    value: ['陳俊宇', '黃琤婷', '林意評', '陳琬惠']
  2024_立委_新竹縣_第一選舉區:
    keys: ['新豐鄉', '湖口鄉', '新埔鎮', '芎林鄉', '關西鎮', '尖石鄉', '竹北市']
    value: ['詹紀緹', '徐欣瑩', '余筱菁', '劉台穠']
  2024_立委_新竹縣_第二選舉區:
    keys: ['竹東鎮', '寶山鄉', '北埔鄉', '峨眉鄉', '橫山鄉', '五峰鄉', '竹北市']
    value: ['曾聖凱', '林思銘', '王婉諭']
  2024_立委_新竹市:
    keys: []
    value: ['林志潔', '鄭正鈐', '柯美蘭', '邱顯智']
  2024_立委_苗栗縣_第一選舉區:
    keys:
      [
        '竹南鎮',
        '後龍鎮',
        '造橋鄉',
        '通霄鎮',
        '西湖鄉',
        '銅鑼鄉',
        '三義鄉',
        '苑裡鎮',
      ]
    value: ['康世明', '陳超明']
  2024_立委_苗栗縣_第二選舉區:
    keys:
      [
        '頭份市',
        '三灣鄉',
        '南莊鄉',
        '苗栗市',
        '公館鄉',
        '頭屋鄉',
        '大湖鄉',
        '獅潭鄉',
        '卓蘭鎮',
        '泰安鄉',
      ]
    value: ['曾玟學', '邱鎮軍']
  2024_立委_彰化縣_第一選舉區:
    keys: ['伸港鄉', '線西鄉', '和美鎮', '鹿港鎮', '福興鄉', '秀水鄉']
    value: ['陳秀寳', '阮厚爵']
  2024_立委_彰化縣_第二選舉區:
    keys: ['彰化市', '花壇鄉', '芬園鄉']
    value: ['黃秀芳', '楊曜聰']
  2024_立委_彰化縣_第三選舉區:
    keys:
      [
        '芳苑鄉',
        '二林鎮',
        '埔鹽鄉',
        '溪湖鎮',
        '埔心鄉',
        '大城鄉',
        '竹塘鄉',
        '埤頭鄉',
        '北斗鎮',
        '溪州鄉',
      ]
    value: ['吳音寧', '謝衣鳳']
  2024_立委_彰化縣_第四選舉區:
    keys: ['員林區', '田中區', '田尾鄉']
    value: ['陳素月', '鄭俊雄']
  2024_立委_南投縣_第一選舉區:
    keys: ['埔里鎮', '草屯鎮', '中寮鄉', '魚池鄉', '國姓鄉', '仁愛鄉']
    value: ['蔡銘軒', '馬文君']
  2024_立委_南投縣_第二選舉區:
    keys: ['南投市', '名間鄉', '集集鎮', '竹山鎮', '鹿谷鄉', '水里鄉', '信義鄉']
    value: ['蔡培慧', '游顥']
  2024_立委_雲林縣_第一選舉區:
    keys:
      [
        '麥寮鄉',
        '臺西鄉',
        '東勢鄉',
        '褒忠鄉',
        '土庫鎮',
        '虎尾鎮',
        '四湖鄉',
        '元長鄉',
        '口湖鄉',
        '水林鄉',
        '北港鎮',
      ]
    value: ['蘇治芬', '丁學忠']
  2024_立委_雲林縣_第二選舉區:
    keys:
      [
        '崙背鄉',
        '二崙鄉',
        '西螺鎮',
        '莿桐鄉',
        '林內鄉',
        '斗六市',
        '大埤鄉',
        '斗南鎮',
        '古坑鄉',
      ]
    value: ['劉建國', '邱良閱']
  2024_立委_嘉義縣_第一選舉區:
    keys:
      [
        '六腳鄉',
        '東石鄉',
        '朴子市',
        '太保市',
        '布袋鎮',
        '義竹鄉',
        '鹿草鄉',
        '水上鄉',
      ]
    value: ['蔡易餘', '詹琬蓁']
  2024_立委_嘉義縣_第二選舉區:
    keys:
      [
        '溪口鄉',
        '大林鎮',
        '梅山鄉',
        '新港鄉',
        '民雄鄉',
        '竹崎鄉',
        '中埔鄉',
        '番路鄉',
        '阿里山鄉',
        '大埔鄉',
      ]
    value: ['陳冠廷', '林國慶']
  2024_立委_嘉義市:
    keys: []
    value: ['王美惠', '陳玥妗', '張秀華']
  2024_立委_屏東縣_第一選舉區:
    keys:
      [
        '里港鄉',
        '高樹鄉',
        '三地門鄉',
        '霧臺鄉',
        '九如鄉',
        '鹽埔鄉',
        '長治鄉',
        '內埔鄉',
        '瑪家鄉',
        '屏東市',
        '麟洛鄉',
      ]
    value: ['鍾佳濱', '黃明賢']
  2024_立委_屏東縣_第二選舉區:
    keys:
      [
        '萬丹鄉',
        '泰武鄉',
        '竹田鄉',
        '萬巒鄉',
        '潮州鎮',
        '新園鄉',
        '崁頂鄉',
        '南州鄉',
        '新埤鄉',
        '來義鄉',
        '東港鎮',
        '林邊鄉',
        '佳冬鄉',
        '枋寮鄉',
        '春日鄉',
        '枋山鄉',
        '獅子鄉',
        '牡丹鄉',
        '車城鄉',
        '滿州鄉',
        '恆春鎮',
        '琉球鄉',
      ]
    value: ['徐富癸', '蘇清泉', '蘇孟淳']
  2024_立委_臺東縣:
    keys: []
    value: ['賴坤成', '劉櫂豪', '黃婉茹', '黃建賓']
  2024_立委_花蓮縣:
    keys: []
    value: ['張美慧', '傅崐萁']
  2024_立委_澎湖縣:
    keys: []
    value: ['楊曜', '吳政杰']
  2024_立委_金門縣:
    keys: []
    value: ['陳玉珍', '尚文凱']
  2024_立委_連江縣:
    keys: []
    value: ['李問', '陳雪生']
  2024_立委_平地原住民:
    keys: []
    value: ['陳瑩', '黃仁', '鄭天財', '陳政宗']
  2024_立委_山地原住民:
    keys: []
    value:
      [
        '伍麗華',
        '孔文吉',
        '盧縣一',
        '高金素梅',
        'Savungaz Valincinan',
        '胡黃廣文',
      ]
