tags:
  - 2024政見
  - 2024帶職參選
  - 性別
  - 生日
  - 出生地
  - 學歷
  - 家庭背景
  - 從政經歷
  - 目前政黨
  - 宗教信仰
  - 兩岸主張
  - 性平主張
  - 犯罪記錄

group:
  2024_總統: ["侯友宜", "趙少康", "賴清德", "蕭美琴","柯文哲", "吳欣盈"]
  2024_立法委員_新北市_第八選舉區: ["吳崢", "張智倫"]
