tags:
  - 2024政見
  - 2024帶職參選
  - 性別
  - 生日
  - 出生地
  - 學歷
  - 家庭背景
  - 從政經歷
  - 目前政黨
  - 宗教信仰
  - 兩岸主張
  - 性平主張
  - 犯罪記錄

group:
  2024_總統: ["侯友宜", "趙少康", "賴清德", "蕭美琴","柯文哲", "吳欣盈"]
  2024_立法委員_臺北市_第一選舉區: ["吳思瑤", "張斯綱", "侯漢廷"]
  2024_立法委員_臺北市_第二選舉區: ["王世堅", "游淑慧"]
  2024_立法委員_臺北市_第三選舉區: ["謝佩芬", "王鴻薇"]
  2024_立法委員_臺北市_第四選舉區: ["高嘉瑜", "李彥秀", "吳欣岱"]
  2024_立法委員_臺北市_第五選舉區: ["吳沛憶", "鍾小平", "于美人"]
  2024_立法委員_臺北市_第六選舉區: ["苗博雅", "羅智強"]
  2024_立法委員_臺北市_第七選舉區: ["許淑華", "徐巧芯"]
  2024_立法委員_臺北市_第八選舉區: ["王閔生", "賴士葆", "賴宣任", "張其祿"]
  2024_立法委員_新北市_第一選舉區: ["何博文", "洪孟楷"]
  2024_立法委員_新北市_第二選舉區: ["林淑芬", "李有宜"]
  2024_立法委員_新北市_第三選舉區: ["李坤城", "蔡明堂"]
  2024_立法委員_新北市_第四選舉區: ["吳秉叡", "蔣欣璋"]
  2024_立法委員_新北市_第五選舉區: ["蘇巧慧", "洪佳君"]
  2024_立法委員_新北市_第六選舉區: ["張宏陸", "林國春"]
  2024_立法委員_新北市_第七選舉區: ["羅致政", "葉元之", "劉書婷"]
  2024_立法委員_新北市_第八選舉區: ["吳崢", "張智倫", "邱臣遠"]
  2024_立法委員_新北市_第九選舉區: ["莊銘淵", "林德福"]
  2024_立法委員_新北市_第十選舉區: ["吳琪銘", "林金結"]
  2024_立法委員_新北市_第十一選舉區: ["曾柏瑜", "羅明才"]
  2024_立法委員_新北市_第十二選舉區: ["賴品妤", "廖先翔"]
  2024_立法委員_桃園市_第一選舉區: ["鄭運鵬", "牛煦庭", "徐鈺雯"]
  2024_立法委員_桃園市_第二選舉區: ["黃世杰", "涂權吉"]
  2024_立法委員_桃園市_第三選舉區: ["彭俊豪", "魯明哲", "徐鶯慈"]
  2024_立法委員_桃園市_第四選舉區: ["范綱祥", "萬美玲"]
  2024_立法委員_桃園市_第五選舉區: ["劉仁照", "呂玉玲", "賴香伶"]
  2024_立法委員_桃園市_第六選舉區: ["趙正宇", "邱若華", "李慕妍"]
  2024_立法委員_臺中市_第一選舉區: ["蔡其昌", "劉燈鐘", "蔡壁如"]
  2024_立法委員_臺中市_第二選舉區: ["林靜儀", "顏寬恆"]
  2024_立法委員_臺中市_第三選舉區: ["謝子涵", "楊瓊瓔"]
  2024_立法委員_臺中市_第四選舉區: ["張廖萬堅", "廖偉翔"]
  2024_立法委員_臺中市_第五選舉區: ["莊競程", "黃健豪", "蔡善雯"]
  2024_立法委員_臺中市_第六選舉區: ["江肇國", "羅廷瑋"]
  2024_立法委員_臺中市_第七選舉區: ["何欣純", "林家興"]
  2024_立法委員_臺中市_第八選舉區: ["謝志忠", "江啟臣"]
  2024_立法委員_臺南市_第一選舉區: ["賴惠員", "周宏昌"]
  2024_立法委員_臺南市_第二選舉區: ["郭國文", "陳昆和"]
  2024_立法委員_臺南市_第三選舉區: ["陳亭妃", "姚正玉"]
  2024_立法委員_臺南市_第四選舉區: ["林宜瑾", "李全教"]
  2024_立法委員_臺南市_第五選舉區: ["林俊憲", "王家貞"]
  2024_立法委員_臺南市_第六選舉區: ["王定宇", "陳以信", "陳永和"]
  2024_立法委員_高雄市_第一選舉區: ["邱議瑩", "曾尹儷"]
  2024_立法委員_高雄市_第二選舉區: ["邱志偉", "曹桓榮"]
  2024_立法委員_高雄市_第三選舉區: ["李柏毅", "李眉蓁"]
  2024_立法委員_高雄市_第四選舉區: ["林岱樺", "陳若翠"]
  2024_立法委員_高雄市_第五選舉區: ["李昆澤", "黃柏霖", "張芳愉"]
  2024_立法委員_高雄市_第六選舉區: ["黃捷", "陳美雅", "郭倍宏"]
  2024_立法委員_高雄市_第七選舉區: ["許智傑", "鍾易仲"]
  2024_立法委員_高雄市_第八選舉區: ["賴瑞隆", "李明璇"]
  2024_立法委員_基隆市: ["鄭文婷", "王醒之", "謝海菁", "林沛祥"]
  2024_立法委員_宜蘭縣: ["陳俊宇", "黃琤婷", "林意評", "陳琬惠"]
  2024_立法委員_新竹縣_第一選舉區: ["詹紀緹", "徐欣瑩", "余筱菁", "劉台穠"]
  2024_立法委員_新竹縣_第二選舉區: ["曾聖凱", "林思銘", "王婉諭"]
  2024_立法委員_新竹市: ["林志潔", "鄭正鈐", "柯美蘭", "邱顯智"]
  2024_立法委員_苗栗縣_第一選舉區: ["康世明", "陳超明"]
  2024_立法委員_苗栗縣_第二選舉區: ["曾玟學", "邱鎮軍"]
  2024_立法委員_彰化縣_第一選舉區: ["陳秀寳", "阮厚爵"]
  2024_立法委員_彰化縣_第二選舉區: ["黃秀芳", "楊曜聰"]
  2024_立法委員_彰化縣_第三選舉區: ["吳音寧", "謝衣鳳"]
  2024_立法委員_彰化縣_第四選舉區: ["陳素月", "鄭俊雄"]
  2024_立法委員_南投縣_第一選舉區: ["蔡銘軒", "馬文君"]
  2024_立法委員_南投縣_第二選舉區: ["蔡培慧", "游顥"]
  2024_立法委員_雲林縣_第一選舉區: ["蘇治芬", "丁學忠"]
  2024_立法委員_雲林縣_第二選舉區: ["劉建國", "邱良閱"]
  2024_立法委員_嘉義縣_第一選舉區: ["蔡易餘", "詹琬蓁"]
  2024_立法委員_嘉義縣_第二選舉區: ["陳冠廷", "林國慶"]
  2024_立法委員_嘉義市: ["王美惠", "陳玥妗", "張秀華"]
  2024_立法委員_屏東縣_第一選舉區: ["鍾佳濱", "黃明賢"]
  2024_立法委員_屏東縣_第二選舉區: ["徐富癸", "蘇清泉", "蘇孟淳"]
  2024_立法委員_臺東縣: ["賴坤成", "劉櫂豪", "黃婉茹", "黃建賓"]
  2024_立法委員_花蓮縣: ["張美慧", "傅崐萁"]
  2024_立法委員_澎湖縣: ["楊曜", "吳政杰"]
  2024_立法委員_金門縣: ["陳玉珍", "尚文凱"]
  2024_立法委員_連江縣: ["李問", "陳雪生"]
  2024_立法委員_平地原住民: ["陳瑩", "黃仁", "鄭天財", "陳政宗"]
  2024_立法委員_山地原住民: ["伍麗華", "孔文吉", "盧縣一", "高金素梅", "Savungaz Valincinan", "胡黃廣文"]
