name: generate data

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - env:
          MIXPANEL_PROJECT_ID: ${{ secrets.MIXPANEL_PROJECT_ID }}
          MIXPANEL_BOOKMARK_ID: ${{ secrets.MIXPANEL_BOOKMARK_ID }}
          MIXPANEL_SECRET: ${{ secrets.MIXPANEL_SECRET }}
        run: |
          node scripts/data.js
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Taiwan Voting Guide
          author_email: taiwan.voting.guide@gmail.com
          message: "Update data"
