name: generate files

on:
  push:
    branches:
      - main
    paths:
      - "content/politician/**"

jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - id: blame
        continue-on-error: true
        run: |
          git diff --no-commit-id --name-only -r HEAD^ | grep "content/politician" | xargs ./scripts/blame.sh
          node ./scripts/contribution.js
      - if: ${{ steps.blame.outcome == 'success' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Taiwan Voting Guide
          author_email: taiwan.voting.guide@gmail.com
          message: "Generate files"
