name: generate files

on:
  push:
    branches:
      - main

jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: blame
        run: |
          git diff-tree --no-commit-id --name-only -r HEAD | grep "content/politician" | xargs ./scripts/blame.sh
      - if: ${{ steps.blame.outcome == 'success' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Taiwan Voting Guide
          author_email: taiwan.voting.guide@gmail.com
          message: "Generate files"

